name: Crafting
version: '${version}'
main: com.unongmilk.crafting.Main
api-version: 1.12

commands:
  craftpotion:
    usage: /craftpotion
  craftpattern:
    usage: /craftpattern
  craftweapon:
    usage: /craftweapon